version: "3.8"
services:
  server:
    image: registry.cn-hangzhou.aliyuncs.com/one-registry/docker-swarm-server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_FILE_NAME=file:local.db
    deploy:
      placement:
        constraints:
          - node.labels.role == server
  case:
    image: registry.cn-hangzhou.aliyuncs.com/one-registry/docker-swarm-case
    depends_on:
      - server
    environment:
      - SERVER_URL=http://10.121.118.11:3000
    deploy:
      replicas: 2  # 或者任意你想要的数量
      placement:
        constraints:
          - node.labels.role == case